### PR TITLE
Game termination

### PR DESCRIPTION
**Pull request by angarita-dev**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hello, devs ✋ Impressive work on your TicTacToe project 😄 👏 And I have a singular observation.

This project follows the lesson about Factory Functions and The Module Pattern so the main goal is to put into practice those concepts along with the main concepts of Object-Oriented Programming. Particularly, classes/objects and how to access their methods and attributes.

Let's separate our code into the `Player` module `Gameboard` and say `Game/Gameplay` and ensure not to mix the dom-manipulation task with the game logic.

Please fix this and request for a re-review 😎 

**Status: `Changes required`**

Happy coding! 😎

**Comment by angarita-dev** [comment]
# Hi @JamesOkunlade and thanks for the feedback! 🥇 
**_About the required changes:_**
>Let's separate our code into the Player module Gameboard and say Game/Gameplay and ensure not to mix the dom-manipulation task with the game logic.

We currently use the `Player` factory function, the modules `data` (logic regarding the board), `domController` (logic regarding all the DOM manipulation) and `gameController` (logic regarding the actual gameplay and integrating `data` and `domController`). That way we keep all the logic separated and the code modular.

We are open to suggestions in order to improve the code quality and other general aspects

**Thanks!👋**

**Comment by JamesOkunlade** [comment]
**Hello, devs!!  ✋ My mistake. I should have mentioned separate  _`into different files`_ 😄**

**Review by JamesOkunlade — APPROVED** [review]
### Great job 👏 😄 It's a 👍 for me.

**Go ahead and merge. Good luck with your future projects.**

**Status: `Approved`**

**Pull request merged**
